=== KercsiBence/ILVIYV_XMLGyak/Feleves beadando/XSDILVIYV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:attribute name="id" type="xs:int"/>

<xs:simpleType name="név">
  <xs:restriction base="xs:string">
    <xs:minLength value="1"/>   
  </xs:restriction>
</xs:simpleType>



<xs:element name="XMLILVIYV">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="vevők">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="vevő" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="név" type="név"/>
                                    <xs:element name="email" type="xs:string"/>
                                    <xs:element name="telefonszám" type="xs:int"/>
                                    <xs:element name="cím"> 
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="irányítószám" type="xs:int"/>
                                                <xs:element name="város" type="xs:string"/>
                                                <xs:element name="utca" type="xs:string"/>
                                                <xs:element name="házszám" type="xs:int"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="rendelések">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="rendelés">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="étterem_id" type="xs:int"/>
                                                            <xs:element name="státusz" type="xs:string"/>
                                                            <xs:element name="leadási_ideje" type="xs:string"/>
                                                            <xs:element name="szállítási_ideje" type="xs:string"/>
                                                            <xs:element name="tranzakció">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="összeg" type="xs:int"/>
                                                                        <xs:element name="kitől" type="xs:int"/>
                                                                        <xs:element name="kinek" type="xs:int"/>
                                                                        <xs:element name="közlemény" type="xs:string"/>
                                                                    </xs:sequence>
                                                                    <xs:attribute ref="id"/>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="ételek">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="étel" maxOccurs="unbounded">
                                                                            <xs:complexType>
                                                                                <xs:sequence>
                                                                                    <xs:element name="ár" type="xs:int"/>
                                                                                    <xs:element name="elkészítési_idő" type="xs:int"/>
                                                                                    <xs:element name="allergének" type="xs:string"/>
                                                                                    <xs:element name="éttermek">
                                                                                        <xs:complexType>
                                                                                            <xs:sequence>
                                                                                                <xs:element name="étterem" maxOccurs="unbounded">
                                                                                                    <xs:complexType>
                                                                                                        <xs:sequence>
                                                                                                            <xs:element name="cím" type="xs:string"/>
                                                                                                            <xs:element name="név" type="xs:string"/>
                                                                                                            <xs:element name="értékelés" type="xs:double"/> 
                                                                                                        </xs:sequence>
                                                                                                        <xs:attribute ref="id"/>
                                                                                                    </xs:complexType>
                                                                                                </xs:element>
                                                                                            </xs:sequence>
                                                                                        </xs:complexType>
                                                                                    </xs:element>
                                                                                </xs:sequence>
                                                                                <xs:attribute name="név" type="xs:string"/>
                                                                            </xs:complexType>
                                                                        </xs:element>
                                                                    </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="futár">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="név" type="xs:string"/>
                                                                        <xs:element name="helyzet" type="xs:string"/>
                                                                        <xs:element name="közlekedés" type="xs:string"/> 
                                                                    </xs:sequence>
                                                                    <xs:attribute ref="id"/>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                        <xs:attribute ref="id"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute ref="id"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:unique name="vevő_id">
        <xs:selector xpath="vevő" />
        <xs:field xpath="@id" />
    </xs:unique>
    <xs:unique name="rendelés_id">
        <xs:selector xpath="rendelés" />
        <xs:field xpath="@id" />
    </xs:unique>
    <xs:unique name="tranzakció_id">
        <xs:selector xpath="tranzakció" />
        <xs:field xpath="@id" />
    </xs:unique>
    <xs:unique name="futár_id">
        <xs:selector xpath="futár" />
        <xs:field xpath="@id" />
    </xs:unique>
    <xs:unique name="étel_név">
        <xs:selector xpath="étel" />
        <xs:field xpath="@név" />
    </xs:unique>
    <xs:unique name="étterem_id">
        <xs:selector xpath="étterem" />
        <xs:field xpath="@id" />
    </xs:unique>

    <xs:keyref refer="vevő_id" name="Rendelés_vevő">
            <xs:selector xpath="rendelés" />
            <xs:field xpath="@vevő_id"/>
    </xs:keyref>
    <xs:keyref refer="rendelés_id" name="Tranzakció_rendelés">
            <xs:selector xpath="tranzakció" />
            <xs:field xpath="@id" />
    </xs:keyref>
    <xs:keyref refer="rendelés_id" name="Futár_rendelés">
            <xs:selector xpath="futár" />
            <xs:field xpath="@id" />
    </xs:keyref>
    <xs:keyref refer="rendelés_id" name="Étel_rendelés">
            <xs:selector xpath="étel" />
            <xs:field xpath="@id" />
    </xs:keyref>
    <xs:keyref refer="étel_név" name="Étterem_étel">
            <xs:selector xpath="étterem" />
            <xs:field xpath="@étel_név" />
    </xs:keyref>
    <xs:keyref refer="étterem_id" name="Rendelés_étterem">
            <xs:selector xpath="rendelés" />
            <xs:field xpath="@étterem_id" />
    </xs:keyref>
</xs:element>




</xs:schema>

=== KercsiBence/ILVIYV_XMLGyak/Feleves beadando/Program/XMLILVIYV.xml
<?xml version="1.0" encoding="UTF-8"?>

<XMLILVIYV>
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XSDILVIYV.xsd">
    <vevők>
        <vevő id="1">
            <név>Kércsi Bence</név>
            <email>kercsibence1@gmail.com</email>
            <telefonszám>01234567890</telefonszám>
            <cím>
                <irányítószám>3535</irányítószám>
                <város>Miskolc</város>
                <utca>Szentgyörgy</utca>
                <házszám>1</házszám>
            </cím>
            <rendelések>
                <rendelés id="1">
                    <étterem_id>1</étterem_id>
                    <státusz>Aktív</státusz>
                    <leadási_ideje>2022-11-10 14:30</leadási_ideje>
                    <szállítási_ideje>2022-11-10 15:45</szállítási_ideje>
                    <tranzakció id="1">
                        <összeg>4500</összeg>
                        <kitől>111</kitől>
                        <kinek>000</kinek>
                        <közlemény>Rántott hús + Töltött káposzta</közlemény>
                    </tranzakció>
                    <ételek>
                        <étel név="Rántott hús">
                            <ár>2000</ár>
                            <elkészítési_idő>32</elkészítési_idő>
                            <allergének>Glutén</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                            </éttermek>
                        </étel>
                        <étel név="Töltött káposzta">
                            <ár>2500</ár>
                            <elkészítési_idő>65</elkészítési_idő>
                            <allergének>Laktóz</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                            </éttermek>
                        </étel>
                    </ételek>
                    <futár id="1">
                        <név>Sándy</név>
                        <helyzet>Avas</helyzet>
                        <közlekedés>Bicikli</közlekedés>
                    </futár>
                </rendelés>
            </rendelések>
        </vevő>
        <vevő id="2">
            <név>Glonczi Bence</név>
            <email>glonczibence@gmail.com</email>
            <telefonszám>01234567891</telefonszám>
            <cím>
                <irányítószám>3535</irányítószám>
                <város>Miskolc</város>
                <utca>Szentgyörgy</utca>
                <házszám>2</házszám>
            </cím>
            <rendelések>
                <rendelés id="2">
                    <étterem_id>1</étterem_id>
                    <státusz>Kiszállítás alatt</státusz>
                    <leadási_ideje>2022-11-10 12:20</leadási_ideje>
                    <szállítási_ideje>2022-11-10 16:35</szállítási_ideje>
                    <tranzakció id="2">
                        <összeg>3500</összeg>
                        <kitől>222</kitől>
                        <kinek>000</kinek>
                        <közlemény>Rántott hús + Borsó leves</közlemény>
                    </tranzakció>
                    <ételek>
                        <étel név="Rántott hús">
                            <ár>2000</ár>
                            <elkészítési_idő>32</elkészítési_idő>
                            <allergének>Glutén</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                            </éttermek>
                        </étel>
                        <étel név="Borsó leves">
                            <ár>1500</ár>
                            <elkészítési_idő>65</elkészítési_idő>
                            <allergének>Laktóz</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                                <étterem id="3">
                                    <cím>Példa cím 3</cím>
                                    <név>Példa étterem 3</név>
                                    <értékelés>4.1</értékelés>
                                </étterem>
                            </éttermek>
                        </étel>
                    </ételek>
                    <futár id="2">
                        <név>Sándor</név>
                        <helyzet>Tapolca</helyzet>
                        <közlekedés>Roller</közlekedés>
                    </futár>
                </rendelés>
            </rendelések>
        </vevő>
        <vevő id="3">
            <név>Kopasz János</név>
            <email>kopaszjanos@gmail.com</email>
            <telefonszám>01234567892</telefonszám>
            <cím>
                <irányítószám>3535</irányítószám>
                <város>Miskolc</város>
                <utca>Arany János</utca>
                <házszám>1</házszám>
            </cím>
            <rendelések>
                <rendelés id="3">
                    <étterem_id>2</étterem_id>
                    <státusz>Aktív</státusz>
                    <leadási_ideje>2022-11-10 12:20</leadási_ideje>
                    <szállítási_ideje>2022-11-11 11:45</szállítási_ideje>
                    <tranzakció id="3">
                        <összeg>3500</összeg>
                        <kitől>333</kitől>
                        <kinek>000</kinek>
                        <közlemény>Hamburger</közlemény>
                    </tranzakció>
                    <ételek>
                        <étel név="Hamburger">
                            <ár>2500</ár>
                            <elkészítési_idő>15</elkészítési_idő>
                            <allergének>Glutén, laktóz</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                                <étterem id="2">
                                    <cím>Példa cím 2</cím>
                                    <név>Példa étterem 2</név>
                                    <értékelés>3.8</értékelés>
                                </étterem>
                                <étterem id="4">
                                    <cím>Példa cím 4</cím>
                                    <név>Példa étterem 4</név>
                                    <értékelés>3.3</értékelés>
                                </étterem>
                                <étterem id="5">
                                    <cím>Példa cím 5</cím>
                                    <név>Példa étterem 5</név>
                                    <értékelés>2.4</értékelés>
                                </étterem>
                            </éttermek>
                        </étel>
                    </ételek>
                    <futár id="3">
                        <név>Shándor</név>
                        <helyzet>Egyetem</helyzet>
                        <közlekedés>Görkori</közlekedés>
                    </futár>
                </rendelés>
            </rendelések>
        </vevő>
        <vevő id="4">
            <név>Szabó Renáta</név>
            <email>szaborenata@gmail.com</email>
            <telefonszám>01234567865</telefonszám>
            <cím>
                <irányítószám>3529</irányítószám>
                <város>Miskolc</város>
                <utca>Arany János tér</utca>
                <házszám>12</házszám>
            </cím>
            <rendelések>
                <rendelés id="4">
                    <étterem_id>2</étterem_id>
                    <státusz>Aktív</státusz>
                    <leadási_ideje>2022-11-10 12:19</leadási_ideje>
                    <szállítási_ideje>2022-11-11 11:46</szállítási_ideje>
                    <tranzakció id="4">
                        <összeg>3500</összeg>
                        <kitől>444</kitől>
                        <kinek>000</kinek>
                        <közlemény>Hamburger</közlemény>
                    </tranzakció>
                    <ételek>
                        <étel név="Hamburger">
                            <ár>2500</ár>
                            <elkészítési_idő>15</elkészítési_idő>
                            <allergének>Glutén, laktóz</allergének>
                            <éttermek>
                                <étterem id="1">
                                    <cím>Példa cím 1</cím>
                                    <név>Példa étterem 1</név>
                                    <értékelés>4.5</értékelés>
                                </étterem>
                                <étterem id="2">
                                    <cím>Példa cím 2</cím>
                                    <név>Példa étterem 2</név>
                                    <értékelés>3.8</értékelés>
                                </étterem>
                                <étterem id="4">
